/**
 * 목 데이터 전용 채번 — 실제로는 DB의 GENERATED BY DEFAULT AS IDENTITY가 담당한다.
 * 모든 PK는 식별자N19(BIGINT) 이므로 number 로 다룬다.
 */
export function nextId<T>(rows: readonly T[], pk: keyof T): number {
  return rows.reduce((max, row) => Math.max(max, Number(row[pk]) || 0), 0) + 1;
}
